const myProjects = [
  {
    id: 1,
    name: "Fast-pizza",
    imgSrc: "/images/fast-pizza.png",
    url: "https://fast-pizza-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs", "redux", "tailwind"],
    rating: 4,
  },
  {
    id: 2,
    name: "Pizza-webapp",
    imgSrc: "/images/pizza-web.png",
    url: "https://pizza-web-app-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript", "scss"],
    rating: 3.4,
  },
  {
    id: 3,
    name: "Home comfort",
    imgSrc: "/images/home-comfort.png",
    url: "https://homecomfort-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
    rating: 3,
  },
  {
    id: 4,
    name: "Paint clone",
    imgSrc: "/images/paint-clone.png",
    url: "https://paint-clone-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
    rating: 4,
  },
  {
    id: 5,
    name: "Tea station",
    imgSrc: "/images/tea-station.png",
    url: "https://tea-station-sameerkindia.netlify.app",
    core: "CSS",
    tecnology: ["CSS"],
    rating: 3.9,
  },
  {
    id: 6,
    name: "Drum kit",
    imgSrc: "/images/drum-kit.png",
    url: "https://drum-kit-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
    rating: 2,
  },
  {
    id: 7,
    name: "Infinity Scroll",
    imgSrc: "/images/infinite-scroll.png",
    url: "https://infinity-scroll-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
    rating: 3,
  },
  {
    id: 8,
    name: "Heart trail",
    imgSrc: "/images/heart-trail.png",
    url: "https://heart-trail-animation-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript", "CSS"],
    rating: 2.3,
  },
  {
    id: 9,
    name: "Grocery bud",
    imgSrc: "/images/grocery-bud.png",
    url: "https://grocery-bud-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
    rating: 3.8,
  },
  {
    id: 10,
    name: "The pizza",
    imgSrc: "/images/the-pizza.png",
    url: "https://the-pizaa-sameerkindia.netlify.app/",
    core: "reactJS",
    tecnology: ["reactJs"],
    rating: 3.5,
  },
  {
    id: 11,
    name: "Cocktail DB",
    imgSrc: "/images/cooktail-db.png",
    url: "https://the-cocktail-db-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
    rating: 3.9,
  },
  {
    id: 12,
    name: "Click bubble",
    imgSrc: "/images/click-bubble.png",
    url: "https://click-bubble-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
    rating: 2.5,
  },
  {
    id: 14,
    name: "Natours",
    imgSrc: "/images/natours.png",
    url: "https://natours-sameerkindia.netlify.app/",
    core: "CSS",
    tecnology: ["CSS"],
    rating: 5,
  },
  {
    id: 13,
    name: "Trillo",
    imgSrc: "/images/trillo-img.png",
    url: "https://trillo-sameerkindia.netlify.app",
    core: "CSS",
    tecnology: ["CSS"],
    rating: 5,
  },
  {
    id: 15,
    name: "Omnifood",
    imgSrc: "/images/omnifood.png",
    url: "https://omnifood-sameerkindia.netlify.app/",
    core: "CSS",
    tecnology: ["CSS"],
    rating: 5,
  },
  {
    id: 16,
    name: "Number range table",
    imgSrc: "/images/number-range.png",
    url: "https://number-range-sameerkindia.netlify.app/",
    core: "javaScript",
    tecnology: ["javaScript"],
    rating: 3,
  },
  {
    id: 17,
    name: "Obys clone",
    imgSrc: "/images/obys.png",
    url: "https://obys-sameerkinda.netlify.app/",
    core: "javaScript",
    tecnology: ["javaScript", "CSS", "locomotive"],
    rating: 4.5,
  },
  {
    id: 18,
    name: "Pinterest HomePage",
    imgSrc: "/images/pinterest.png",
    url: "https://pinterest-sameerkindia.netlify.app/",
    core: "React Js",
    tecnology: ["React js"],
    rating: 4,
  },
  {
    id: 19,
    name: "Mazano",
    imgSrc: "/images/mazano.png",
    url: "https://mazano-sameerkinda.netlify.app/",
    core: "Next JS",
    tecnology: ["Next js", "Tailwind css"],
    rating: 4.1,
  },
];

//

export default myProjects;
