const myProjects = [
  {
    id: 1,
    name: "Fast-pizza",
    imgSrc: "/images/fast-pizza.png",
    url: "https://fast-pizza-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs", "redux", "tailwind"],
  },
  {
    id: 2,
    name: "Pizza-webapp",
    imgSrc: "/images/pizza-web.png",
    url: "https://pizza-web-app-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript", "scss"],
  },
  {
    id: 3,
    name: "Home comfort",
    imgSrc: "/images/home-comfort.png",
    url: "https://homecomfort-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 4,
    name: "Paint clone",
    imgSrc: "/images/paint-clone.png",
    url: "https://paint-clone-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 5,
    name: "Tea station",
    imgSrc: "/images/tea-station.png",
    url: "https://tea-station-sameerkindia.netlify.app",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 6,
    name: "Drum kit",
    imgSrc: "/images/drum-kit.png",
    url: "https://drum-kit-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 7,
    name: "Infinity Scroll",
    imgSrc: "/images/infinite-scroll.png",
    url: "https://infinity-scroll-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 8,
    name: "Heart trail",
    imgSrc: "/images/heart-trail.png",
    url: "https://heart-trail-animation-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript", "CSS"],
  },
  {
    id: 9,
    name: "Grocery bud",
    imgSrc: "/images/grocery-bud.png",
    url: "https://grocery-bud-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 10,
    name: "The pizza",
    imgSrc: "/images/the-pizza.png",
    url: "https://the-pizaa-sameerkindia.netlify.app/",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 11,
    name: "Cocktail DB",
    imgSrc: "/images/cooktail-db.png",
    url: "https://the-cocktail-db-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 12,
    name: "Click bubble",
    imgSrc: "/images/click-bubble.png",
    url: "https://click-bubble-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 15,
    name: "Natours",
    imgSrc: "/images/natours.png",
    url: "https://natours-sameerkindia.netlify.app/",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 13,
    name: "Trillo",
    imgSrc: "/images/trillo-img.png",
    url: "https://trillo-sameerkindia.netlify.app",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 14,
    name: "Omnifood",
    imgSrc: "/images/omnifood.png",
    url: "https://omnifood-sameerkindia.netlify.app/",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 16,
    name: "Number range table",
    imgSrc: "/images/number-range.png",
    url: "https://number-range-sameerkindia.netlify.app/",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
];

export default myProjects;
