const myProjects = [
  {
    id: 1,
    name: "Fast-pizza",
    url: "https://fast-pizza-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs", "redux", "tailwind"],
  },
  {
    id: 2,
    name: "Pizza-webapp",
    url: "https://pizza-web-app-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript", "scss"],
  },
  {
    id: 3,
    name: "Home comfort",
    url: "https://homecomfort-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 4,
    name: "Paint clone",
    url: "https://paint-clone-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 5,
    name: "Tea station",
    url: "https://tea-station-sameerkindia.netlify.app",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 6,
    name: "Drum kit",
    url: "https://drum-kit-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 7,
    name: "Infinity Scroll",
    url: "https://infinity-scroll-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 8,
    name: "Heart trail",
    url: "https://heart-trail-animation-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript", "CSS"],
  },
  {
    id: 9,
    name: "Grocery bud",
    url: "https://grocery-bud-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 10,
    name: "The pizza",
    url: "https://the-pizaa-sameerkindia.netlify.app/",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 11,
    name: "Cocktail DB",
    url: "https://the-cocktail-db-sameerkindia.netlify.app",
    core: "reactJS",
    tecnology: ["reactJs"],
  },
  {
    id: 12,
    name: "Click bubble",
    url: "https://click-bubble-sameerkindia.netlify.app",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
  {
    id: 15,
    name: "Natours",
    url: "https://natours-sameerkindia.netlify.app/",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 13,
    name: "Trillo",
    url: "https://trillo-sameerkindia.netlify.app",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 14,
    name: "Omnifood",
    url: "https://omnifood-sameerkindia.netlify.app/",
    core: "CSS",
    tecnology: ["CSS"],
  },
  {
    id: 16,
    name: "Number range table",
    url: "https://number-range-sameerkindia.netlify.app/",
    core: "javaScript",
    tecnology: ["javaScript"],
  },
];

export default myProjects;
